<?php
$title = "marmitas";
$marmitas = array(
    0 => array ('id'=>'1', 'titulo'=>'Arroz com Macarrão Cabelo de Anjo', 'descricao'=>'Uma opção exótica ao arroz branco de todo dia, este prato de origem Síria leva ingredientes básicos e econômicos. Acompanha muito bem diversos tipos de carne e frango, especialmente as receitas típicas do Oriente Médio, como kaftas e quibes.','tamanho'=>'media','preco'=>'R$:14,90.','imagem'=>'img/arroz.jpeg'),
    1 => array ('id'=>'2', 'titulo'=>'Bacalhau com Molho de tomate e batatas na manteiga', 'descricao'=>'Essa receita é perfeita para quem gosta de bacalhau: prática e muito saborosa. Aqui, o bacalhau é combinado com um molho de tomate cheio de sabor: você̂ vai aprender a fazê-lo em casa e a combiná-lo com azeitona, tomilho, alho- poró… fica incrível! Para finalizar, tem batatas na manteiga com alecrim.','tamanho'=>'media','preco'=>'R$:18,50.','imagem'=>'img/bacalhau.jpg'),
    2 => array ('id'=>'3', 'titulo'=>'Batatas ao Murro com Alecrim', 'descricao'=>'Essa é uma receita para se ter sempre na manga! As Batatas ao Murro com Alecrim, além de deliciosas, são versáteis. Elas são o acompanhamento perfeito para várias receitas','tamanho'=>'media','preco'=>'R$:15,90','imagem'=>'img/batatas.jpg'),
    3 => array ('id'=>'4', 'titulo'=>'Camarão ao Cabelo de Anjo e Molho Thai', 'descricao'=>'Essa receita é diferente e deliciosa. Os camarões são envolvidos no macarrão cabelo de anjo – eles vão ao forno, e os finos fios de macarrão ficam muito crocantes! Para completar, o molho thai traz potência de sabor e valoriza ainda mais os camarões. Delicioso e inesquecível!','tamanho'=>'media','preco'=>'R$:17,50.','imagem'=>'img/camarao.jpg'),
    4 => array ('id'=>'5', 'titulo'=>'Cuscuz Nordestino de Milho', 'descricao'=>'Um sabor surpreendente! Pode acreditar: você vai querer comer este cuscuz inteiro sozinho. Tem o salgadinho do queijo de coalho, o doce da banana… um sabor surreal. Uma das melhores receitas de cuscuz que já́ comi.','tamanho'=>'media','preco'=>'R$:14,90','imagem'=>'img/cuscuz.jpg'),
    5 => array ('id'=>'6', 'titulo'=>'Legumes Caramelizados', 'descricao'=>'Legumes caramelizados são maravilhosos como acompanhamento de pratos no dia a dia. Cada um deles tem um sabor particular – e é a mistura desses sabores que muda tudo na boca. São macios e caramelizados ao mesmo tempo e, por isso, ligeiramente crocantes. Sensacional!','tamanho'=>'media','preco'=>'R$:16,90','imagem'=>'img/legumes.jpg'),
    6 => array ('id'=>'7', 'titulo'=>'Maionese de Batata Especial', 'descricao'=>'A receita desta salada de batata com maionese foi ensinada ao meu pai há muitos anos por um amigo seu que emigrou da extinta Tchecoslováquia para o Brasil. Quando experimentamos pela primeira vez, já́ nos apaixonamos. Desde então, passamos a preparar com frequência em casa, em reuniões de família e amigos. Não tem uma vez que ela não faça sucesso. O crispy de bacon e os picles de pepino trazem uma crocância e um sabor que são indescritíveis, só́ provando para entender a delícia que é. Além disso, é superversátil e acompanha muito bem diversos tipos de carnes e aves','tamanho'=>'media','preco'=>'R$:13,90','imagem'=>'img/maionese.jpg'),
    7 => array ('id'=>'8', 'titulo'=>'Molho de Aparas de Carnes', 'descricao'=>'Esse molho é suave e, ao mesmo tempo, delicioso. Ele traz a potência do sabor da carne. Nos pratos em que a carne é protagonista, o molho é o acompanhamento ideal!','tamanho'=>'media','preco'=>'R$:19,90','imagem'=>'img/molho.jpg'),

);

?>